"""
This module defines the database models for the application.

Classes:
- User: Represents a user in the system.
- Transaction: Represents a financial transaction.
- Category: Represents a category for grouping transactions.
- Budget: Represents a budget for managing expenses.
- Goal: Represents a financial goal.
- Report: Represents a generated report.
- Insight: Represents an insight generated by the system.
- Notification: Represents a notification for the user.
"""

from app import db, login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(db.Model, UserMixin):
    """
    Represents a user in the system.

    Fields:
        - id: The unique identifier for the user.
        - username: The username of the user.
        - first_name: The first name of the user.
        - last_name: The last name of the user.
        - email: The email address of the user.
        - password_hash: The hashed password of the user.

    Methods:
        - set_password: Set the password for the user.
        - check_password: Check if the password is correct for the user.
    """
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)

    # Define relationships:
    transactions = db.relationship('Transaction', back_populates='user')
    budgets = db.relationship('Budget', back_populates='user')
    goals = db.relationship('Goal', back_populates='user')
    insights = db.relationship('Insight', back_populates='user')
    notifications = db.relationship('Notification', back_populates='user')
    reports = db.relationship('Report', back_populates='user')

    def set_password(self, password):
        """
        Set the password for the user.

        Args:
            password (str): The password to set.

        Returns:
            None
        """
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """
        Check if the password is correct for the user.

        Args:
            password (str): The password to check.

        Returns:
            bool: True if the password is correct, False otherwise.
        """
        return check_password_hash(self.password_hash, password)

    def get_id(self):
        return str(self.id)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id)) # slightly modified such that the user is loaded based on the id in the db
        

class Transaction(db.Model):
    """
    Represents a financial transaction.

    Fields:
    - id: The unique identifier for the transaction.
    - date: The date of the transaction.
    - description: The description of the transaction.
    - amount: The amount of the transaction.
    - category_id: The foreign key to the category of the transaction.
    - category: The relationship to the category of the transaction.
    - user_id: The foreign key to the user associated with the transaction.
    - user: The relationship to the user associated with the transaction.
    """
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date)
    description = db.Column(db.String(255))
    amount = db.Column(db.Float)

    # Foreign keys
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    # Define relationships:
    user = db.relationship('User', back_populates='transactions')
    category = db.relationship('Category', back_populates='transactions')

class Category(db.Model):
    """
    Represents a category for grouping transactions.

    Fields:
    - id: The unique identifier for the category.
    - name: The name of the category.
    - transactions: The relationship to the transactions in the category.
    - user_id: The foreign key to the user associated with the category.
    - user: The relationship to the user associated with the category.
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))

    # Relationships
    transactions = db.relationship('Transaction', back_populates='category')

class Budget(db.Model):
    """
    Represents a budget for managing expenses.

    Fields:
    - id: The unique identifier for the budget.
    - name: The name of the budget.
    - total_budgeted_amount: The total budgeted amount for the budget.
    - user_id: The foreign key to the user associated with the budget.
    - user: The relationship to the user associated with the budget.
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    total_budgeted_amount = db.Column(db.Float)

    # Define foreign keys
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    # Define relationship
    user = db.relationship('User', back_populates='budgets')

class Goal(db.Model):
    """
    Represents a financial goal.

    Fields:
    - id: The unique identifier for the goal.
    - name: The name of the goal.
    - target_amount: The target amount for the goal.
    - user_id: The foreign key to the user associated with the goal.
    - user: The relationship to the user associated with the goal.
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    goal_type = db.Column(db.String(50))
    generation_date = db.Column(db.DateTime, default=datetime.utcnow)

    # Define foreign keys
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    # Define relationships
    user = db.relationship('User', back_populates='goals')

class Insight(db.Model):
    """
    Represents an insight generated by the system.

    Fields:
    - id: The unique identifier for the insight.
    - content: The content of the insight.
    - generation_date: The date the insight was generated.
    - user_id: The foreign key to the user associated with the insight.
    - user: The relationship to the user associated with the insight.
    """
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    generation_date = db.Column(db.DateTime, default=datetime.utcnow)

    # Define foreign keys
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    # Define relationships
    user = db.relationship('User', back_populates='insights')

class Notification(db.Model):
    """
    Represents a notification for the user.

    Fields:
    - id: The unique identifier for the notification.
    - title: The title of the notification.
    - content: The content of the notification.
    - timestamp: The timestamp of the notification.
    - user_id: The foreign key to the user associated with the notification.
    - user: The relationship to the user
    """
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    content = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    # Define foreign keys
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    # Define relationships
    user = db.relationship('User', back_populates='notifications')

class Report(db.Model):
    """
    Represents a generated report.

    Fields:
    - id: The unique identifier for the report.
    - name: The name or title of the report.
    - content: The content of the report, which can include transaction details.
    - start_date: The start date of the report's time range.
    - end_date: The end date of the report's time range.
    - timestamp: The timestamp of the report's generation.
    - user_id: The foreign key to the user associated with the report.
    - user: The relationship to the user associated with the report.
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    content = db.Column(db.Text)
    start_date = db.Column(db.Date)
    end_date = db.Column(db.Date)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    # Define foreign keys
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    # Define relationships
    user = db.relationship('User', back_populates='reports')

    def generate_pdf_report(self):
        """
        Generate a PDF report based on the report's content.

        You'll need to implement the logic for generating a PDF report here.
        """
        # Placeholder for generating PDF report
        # You can use libraries like ReportLab or pdfkit for PDF generation
        pass

    def generate_csv_report(self):
        """
        Generate a CSV report based on the report's content.

        You'll need to implement the logic for generating a CSV report here.
        """
        # Placeholder for generating CSV report
        # You can use libraries like csv or pandas for CSV generation
        pass