"""Modify Model Relationships && Add Report Model

Revision ID: 0ffe234e0244
Revises: 056fe24c1b5f
Create Date: 2023-10-14 01:24:36.874550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ffe234e0244'
down_revision = '056fe24c1b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('generation_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('target_amount')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('generation_date')
        batch_op.drop_column('report_type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('generation_date', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('content')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_amount', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('generation_date')
        batch_op.drop_column('goal_type')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('category_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
