"""Add cashflow, category, mode and change description to comment in Transaction

Revision ID: 216eb21e7173
Revises: 0ffe234e0244
Create Date: 2023-10-16 13:34:00.789746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '216eb21e7173'
down_revision = '0ffe234e0244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashflow', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('comment')
        batch_op.drop_column('mode')
        batch_op.drop_column('cashflow')

    # ### end Alembic commands ###
